services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/cabana:/cabana
    working_dir: /cabana

  flask-api:
    build: ./api
    ports:
      - "5900:5000"
    volumes:
      - ./api:/api
    env_file: 
      - ./.env
    environment:
      - FLASK_APP=index.py