version: "3.8"

services:
  nextjs:
    image: bpetselis01/nextjs:latest  # Pull from Docker Hub instead of building
    container_name: nextjs-container
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend/cabana:/cabana

  flask-api:
    image: bpetselis01/flask-api:latest  # Pull from Docker Hub instead of building
    container_name: flask-api-container
    ports:
      - "5900:5000"
    restart: always
    volumes:
      - ./flask-api:/flask-api
    environment:
      - FLASK_APP=index.py
