services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"

  flask-api:
    build: ./api
    ports:
      - "5900:5000"
    volumes:
      - ./api:/api
    env_file: 
      - path: ./.env
    environment:
      - FLASK_APP=index.py

