name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  push:
    branches: [ "deployment_test_byron" ] 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Latest Docker Images
        run: |
          docker pull bpetselis01/flask-api:latest
          docker pull bpetselis01/nextjs:latest

      - name: Stop and Remove Old Containers
        run: |
          docker-compose down || true

      - name: Start Services with Docker Compose
        run: |
          docker-compose up -d
