name: Docker Image CI

on:
  push:
    branches: [ "deployment_test_byron" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Flask API Docker image
      run: docker build -t flask-api -f flask-api/Dockerfile .

    - name: Build the Frontend Docker image
      run: docker build -t nextjs-app -f frontend/Dockerfile .

    - name: Push to Dockerhub
      run: docker push bpetselis01/cicd-pipeline:latest


