name: Unit Tests

on:
  push:
    branches:
      - main
      - noor/testing
      - STAGING_ENV
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r testing/requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/api" >> $GITHUB_ENV

      - name: Run Tests
        working-directory: testing
        run: pytest --cov=../api --cov-report=html:unittest_report --cov-report=term-missing

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: unittest_report
          path: testing/unittest_report