name: Unit Tests

on:
  push:
    branches:
      - main
      - noor/s2_testing
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r testing/requirements.txt
          sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/api" >> $GITHUB_ENV

      - name: Run Unit Tests
        working-directory: testing
        run: pytest --cov=../api --cov-report=html:unittest_report --cov-report=term-missing

      - name: Convert Coverage Report to PDF
        working-directory: testing
        run: |
          wkhtmltopdf unittest_report/index.html unittest_report.pdf

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: testing/unittest_report.pdf