name: Unit Tests

on:
  push:
    branches:
      - main
      - noor/s2_testing
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r testing/requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/.." >> $GITHUB_ENV  # Use parent directory

      - name: Run Unit Tests
        working-directory: testing
        run: pytest --cov=../api --cov-report=html --cov-report=term-missing  # Debug coverage output