name: Run API Tests

on:
  push:
    branches: [ "main", "STAGING_ENV" ]
  pull_request:
    branches: [ "main", "STAGING_ENV" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test script
        working-directory: ./api
        run: python test.py