name: Unit Tests

on:
  push:
    branches:
      - main
      - noor/s2_testing
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r testing/requirements.txt
          pip install pytest pytest-cov

      - name: Run Unit Tests
        run: pytest tests --cov=src --cov-report=xml

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true